### ISSUE TITLE
Possibility to set UID and GID of omero-server user

### ISSUE THREAD

**Issue by tstoeter** [ome/docker-example-omero#18]
Is there a possibility for the omero server container to set the UID and GID of the omero-server user, i.e. to respect the user setting from the `docker-compose.yml`?

```
  ...
  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-server:5"
    user: 1234:2468
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
    ...
```

This would facilitate managing permissions of bind mounts for data storage on the host, e.g. having `/OMERO` on the host file system.

Currently, the omero-server user has 1000:992 as fixed UID:GID.
